### ISSUE TITLE
Marco review

### ISSUE THREAD

**Issue by emanjon** [EricssonResearch/ace-ake-authz#14]
https://mailarchive.ietf.org/arch/msg/lake/5fR1AitD4XRuWf18OgGbtwge40U/

Please see below my comments about draft-selander-lake-authz-00 [1].

Best,
/Marco

[1] https://datatracker.ietf.org/doc/html/draft-selander-lake-authz-00

======================

[Section 3.2]

* "In this version of the draft is assumed that V authenticates to W 
with the public key PK_V using some authentication protocol providing 
proof of possession of the private key, for example TLS 1.3 [RFC8446]."

    It is fine (although excessive) to assume that, but later on the 
voucher is intended to be computed over the whole authentication 
credential CRED_R, not only on the public key PK_V.

    When establishing the secure session between V and W, it might not 
have been possible to use exactly CRED_R for authenticating V. In 
particular, CRED_R has to be a CCS, which might not be accepted as is by 
the (D)TLS handshake as raw public key of the (D)TLS client.

    Basically, out of the secure association establishment with V, W 
knows the public key PK_V, but it might not know the exact CRED_R to 
compute the Voucher.

    As per Section 4.3.2, "The voucher is essentially a message 
authentication code which binds the authentication credential of V to 
message_1 of EDHOC", so the whole authentication credential has to be 
considered.

    Why not entirely decoupling the two ways that V uses to authenticate 
with U and with W? See further comments below.

* "A future version of this draft may specify explicit proof of 
possession of the private key of PK_V in VREQ, e.g., by including a 
signature of the contents of the voucher request made with the private 
key corresponding to PK_V."

    Yes, this would be much better and more flexible.

    The Voucher Request can include the whole authentication credential 
CRED_R, together with the Proof-of-Possession (PoP) evidence PoP_V. 
After all, the leg V-W is supposed to rely on a non-constrained link.

    To admit both signing and Diffie-Hellman CRED_R (without mixing up 
authentication in the U-V leg with that in the V-W leg), the PoP 
evidence PoP_V can be:

       - A signature, if CRED_R includes a signing public key.

       - A MAC, if CRED_R includes a Diffie-Hellman public key. The MAC 
can be computed be means of a key, derived from a Diffie-Hellman secret 
and the EDHOC G_X as salt.

          The Diffie-Hellman secret can be computed using the 
public/private key corresponding to CRED_R, as well as the public key 
G_W and the corresponding private key. This assumes that V has the 
Diffie-Hellman public key of W, or that it can retrieve it latest when 
preparing the Voucher Request.

        This is the same approach used to build Proof-of-Possession in 
draft-ietf-ace-key-groupcomm-oscore and 
draft-tiloca-ace-group-oscore-profile.

[Section 3.3]

* "W may provide V with the authorization credential of U, CRED_I, after 
V has learnt the identity of U."

    Do you mean "authentication credential", right? But isn't that in 
fact the identity of U?

    Do you rather mean "after V has learnt ID_CRED_I", i.e., following 
the decryption of message_3? That's what Figure 2 and the text in 
Section 4.4.3.2 suggest.

    As to "may provide": this is just to still admit U to specify its 
certificate by value in CRED_I, correct? So this still remains possible.

    If the idea is for V to request CRED_I from W, what is specified in 
ID_CRED_I as a reference to CRED_I? Since such a reference is relevant 
for W (and it might collide with other references stored at V as related 
to totally different peers than U), how do you tell V that such a 
reference is actually to be forwarded to W and consumed by W?

    Perhaps you can have ID_CRED_I specifying a URI, which points to a 
resource at W and whose path includes an identifier that W understands 
as related to the CRED_I to provide to V.

[Section 4.4.2.2]

* This implies that, at least for this particular EDHOC execution 
involving this particular use of EAD items, U considers a TOFU policy 
for trusting any new authentication credentials as long as they are 
valid, right?

[Section 4.5.1.1]

* See the comments above for Section 3.2, i.e., I would always include 
CRED_R and PoP_V, unless exactly CRED_R was used when establishing the 
secure association between V and W together with V's authentication 
(which feels like a corner case).

    That approach would also dismiss the problem when V authenticates to 
U with static Diffie-Hellman and to W with a signature.

* "Editor's note: Define PoP_V (include G_X, ENC_ID in the calculation 
for binding to this EDHOC session)."

    When working on draft-ietf-ace-key-groupcomm-oscore, Jim suggested 
that a PoP evidence (like PoP_V here) should always cover also 
information generated by the peer that computes the PoP evidence.

    Instead, none of the pieces of information intended to be covered by 
the PoP evidence is genered by V. Hence, you may need anyway also a 
further nonce generated by V and different than the EDHOC G_X, to be 
included in the Voucher Request and covered by PoP_V. Perhaps the EDHOC 
G_Y would do the work?

[Section 4.5.2.1]

* "W retrieves the public key of V, PK_V, used to authenticate the 
secure connection with V, and constructs the CCS ... Editor's note: Make 
sure the CCS is defined to allow W generate it uniquely from PK_V."

    Right, which exact CCS? Simply the public key as COSE_Key, 
surrounded by 'cnf' as the only element of an outer map?

    That's not flexible in general, as the outer map can also include 
additional information that W may not be aware of.

    As above, I think that, except in very particular corner cases, V 
has to provide W with the full authentication credential CRED_R in the 
Voucher Request, together with PoP_V.

[Section 5]

* "In both cases, V MUST perform client authentication to authenticate 
to W, using a certificate containing the PK_V public key."

   As above, I would totally decouple the secure association between V 
and W from the CRED_R used by V to authenticate to U in EDHOC.

   This has the following advantages:

      - You don't need to mandate (D)TLS client authentication between V 
and W. Besides, if you still use it, it does not have to necessarily 
rely on client certificates.

      - You don't need to come up with a canonical way for W to build a 
CCS including the public key PK_V.

      - You don't need to worry about V authenticating to W with a 
signature and to U with static Diffie-Hellman.

[Section 6]

* "W may be used for lookup of CRED_I from ID_CRED_I, or this credential 
lookup function may be separate from the authorization function of W."

    This is easier to visualize when looking at Figure 2 in Section 4.1, 
so it would be good to refer it in this sentence.

    Also related to a previous comment about Section 3.3, a possible 
construction for this particular EDHOC execution can be:

    - If ID_CRED_I contains CRED_I by value, V takes CRED_I from 
ID_CRED_I. This assumes that V is already storing CRED_I or that it 
relies on a TOFU trust model, at the very least for this EDHOC execution 
using these particular EAD items.

    - If ID_CRED_I contains a reference to CRED_I different than a URI, 
V fetches CRED_I from its local storage as normally expected.

    - If ID_CRED_I contains a reference to CRED_I as a URI, V fetches 
CRED_I from the indicated URI, which has to include an identifier of 
CRED_I that is meaningful for the contacted server where to fetch CRED_I 
from. As per a comment above, this URI can practically point to a 
resource at W.

**Comment by gselander** [comment]
Thanks, Marco, for comments! Sorry for very slow response, but the comments did have an impact on the content of the protocol which required some rewrite. I think the comments are addressed by the current master version, please object otherwise.

Comments inline:


[Section 3.2]

* "In this version of the draft is assumed that V authenticates to W 
with the public key PK_V using some authentication protocol providing 
proof of possession of the private key, for example TLS 1.3 [RFC8446]."

    It is fine (although excessive) to assume that, but later on the 
voucher is intended to be computed over the whole authentication 
credential CRED_R, not only on the public key PK_V.

    When establishing the secure session between V and W, it might not 
have been possible to use exactly CRED_R for authenticating V. In 
particular, CRED_R has to be a CCS, which might not be accepted as is by 
the (D)TLS handshake as raw public key of the (D)TLS client.

    Basically, out of the secure association establishment with V, W 
knows the public key PK_V, but it might not know the exact CRED_R to 
compute the Voucher.

    As per Section 4.3.2, "The voucher is essentially a message 
authentication code which binds the authentication credential of V to 
message_1 of EDHOC", so the whole authentication credential has to be 
considered.

    Why not entirely decoupling the two ways that V uses to authenticate 
with U and with W? See further comments below.


[GS:] This decoupling was done with PR #15.


* "A future version of this draft may specify explicit proof of 
possession of the private key of PK_V in VREQ, e.g., by including a 
signature of the contents of the voucher request made with the private 
key corresponding to PK_V."

    Yes, this would be much better and more flexible.

    The Voucher Request can include the whole authentication credential 
CRED_R, together with the Proof-of-Possession (PoP) evidence PoP_V. 
After all, the leg V-W is supposed to rely on a non-constrained link.

    To admit both signing and Diffie-Hellman CRED_R (without mixing up 
authentication in the U-V leg with that in the V-W leg), the PoP 
evidence PoP_V can be:

       - A signature, if CRED_R includes a signing public key.

       - A MAC, if CRED_R includes a Diffie-Hellman public key. The MAC 
can be computed be means of a key, derived from a Diffie-Hellman secret 
and the EDHOC G_X as salt.

          The Diffie-Hellman secret can be computed using the 
public/private key corresponding to CRED_R, as well as the public key 
G_W and the corresponding private key. This assumes that V has the 
Diffie-Hellman public key of W, or that it can retrieve it latest when 
preparing the Voucher Request.

        This is the same approach used to build Proof-of-Possession in 
draft-ietf-ace-key-groupcomm-oscore and 
draft-tiloca-ace-group-oscore-profile.

[GS:] The proof-of-possession need only happen rarely for each pair of (V,W), and is now assumed to be carried out before the protocol specified in this draft. We propose PoP to be carried out with EDHOC over the non-constrained network, because it seemed simpler from a deployment point of view to make use of an existing implementation.


[Section 3.3]

* "W may provide V with the authorization credential of U, CRED_I, after 
V has learnt the identity of U."

    Do you mean "authentication credential", right? But isn't that in 
fact the identity of U?

    Do you rather mean "after V has learnt ID_CRED_I", i.e., following 
the decryption of message_3? That's what Figure 2 and the text in 
Section 4.4.3.2 suggest.

[GS:] This text is rewritten. We now use the terms “device identifier” for ID_U to distinguish from the authentication credential CRED_U.


    As to "may provide": this is just to still admit U to specify its 
certificate by value in CRED_I, correct? So this still remains possible.

[GS:] Yes, and is highlighted in the new text.


    If the idea is for V to request CRED_I from W, what is specified in 
ID_CRED_I as a reference to CRED_I? Since such a reference is relevant 
for W (and it might collide with other references stored at V as related 
to totally different peers than U), how do you tell V that such a 
reference is actually to be forwarded to W and consumed by W?

    Perhaps you can have ID_CRED_I specifying a URI, which points to a 
resource at W and whose path includes an identifier that W understands 
as related to the CRED_I to provide to V.

[GS:] Hopefully this is more clear following the distinction between device identifier and authentication credential. The device identifier may be from a separate name space searchable for W. ID_CRED_I is using COSE headers in the way EDHOC does to identify


[Section 4.4.2.2]

* This implies that, at least for this particular EDHOC execution 
involving this particular use of EAD items, U considers a TOFU policy 
for trusting any new authentication credentials as long as they are 
valid, right?

[GS:] I think this interpretation of Trust On First Use is a bit stretched. U receives CRED_V in message_2 together with the voucher in EAD_2 and verifies the former with the latter. So, yes, CRED_V has not been used before and it is trusted the first time it is used. But, no, this is not trusting any credential because there is a voucher being verified. I would call this a TTP policy, not a TOFU policy.


[Section 4.5.1.1]

* See the comments above for Section 3.2, i.e., I would always include 
CRED_R and PoP_V, unless exactly CRED_R was used when establishing the 
secure association between V and W together with V's authentication 
(which feels like a corner case).

    That approach would also dismiss the problem when V authenticates to 
U with static Diffie-Hellman and to W with a signature.

[GS:] As discussed above, the protocol is changed on this point.


* "Editor's note: Define PoP_V (include G_X, ENC_ID in the calculation 
for binding to this EDHOC session)."

    When working on draft-ietf-ace-key-groupcomm-oscore, Jim suggested 
that a PoP evidence (like PoP_V here) should always cover also 
information generated by the peer that computes the PoP evidence.

    Instead, none of the pieces of information intended to be covered by 
the PoP evidence is genered by V. Hence, you may need anyway also a 
further nonce generated by V and different than the EDHOC G_X, to be 
included in the Voucher Request and covered by PoP_V. Perhaps the EDHOC 
G_Y would do the work?


[GS:] As discussed above, the protocol is changed on this point. Now EDHOC is recommended as PoP. So, indeed, both G_X and G_Y are included :-)


[Section 4.5.2.1]

* "W retrieves the public key of V, PK_V, used to authenticate the 
secure connection with V, and constructs the CCS ... Editor's note: Make 
sure the CCS is defined to allow W generate it uniquely from PK_V."

    Right, which exact CCS? Simply the public key as COSE_Key, 
surrounded by 'cnf' as the only element of an outer map?

    That's not flexible in general, as the outer map can also include 
additional information that W may not be aware of.

    As above, I think that, except in very particular corner cases, V 
has to provide W with the full authentication credential CRED_R in the 
Voucher Request, together with PoP_V.


[GS:] As above.


[Section 5]

* "In both cases, V MUST perform client authentication to authenticate 
to W, using a certificate containing the PK_V public key."

   As above, I would totally decouple the secure association between V 
and W from the CRED_R used by V to authenticate to U in EDHOC.

   This has the following advantages:

      - You don't need to mandate (D)TLS client authentication between V 
and W. Besides, if you still use it, it does not have to necessarily 
rely on client certificates.

      - You don't need to come up with a canonical way for W to build a 
CCS including the public key PK_V.

      - You don't need to worry about V authenticating to W with a 
signature and to U with static Diffie-Hellman.


[GS:] As above.


[Section 6]

* "W may be used for lookup of CRED_I from ID_CRED_I, or this credential 
lookup function may be separate from the authorization function of W."

    This is easier to visualize when looking at Figure 2 in Section 4.1, 
so it would be good to refer it in this sentence.


[GS:] Done

    Also related to a previous comment about Section 3.3, a possible 
construction for this particular EDHOC execution can be:

    - If ID_CRED_I contains CRED_I by value, V takes CRED_I from 
ID_CRED_I. This assumes that V is already storing CRED_I or that it 
relies on a TOFU trust model, at the very least for this EDHOC execution 
using these particular EAD items.

    - If ID_CRED_I contains a reference to CRED_I different than a URI, 
V fetches CRED_I from its local storage as normally expected.

    - If ID_CRED_I contains a reference to CRED_I as a URI, V fetches 
CRED_I from the indicated URI, which has to include an identifier of 
CRED_I that is meaningful for the contacted server where to fetch CRED_I 
from. As per a comment above, this URI can practically point to a 
resource at W.

[GS:] As above, the trust model does not build on TOFU (in the sense understood be me) nor that the authentication credential is stored in advance. So it is not clear to me where this processing should be described

**Comment by gselander** [comment]
Closing this as comments are adressed.
